service: serverless-ipsum 
frameworkVersion: ">=1.28.0 <2.0.0"

provider:
  name: aws
  runtime: go1.x
  stage: prod
  region: ap-south-1

package:
 exclude:
   - ./**
 include:
   - ./bin/**

functions:
  hello:
    handler: bin/ipsum
    events:
      - http:
          path: /
          method: get